from django.conf.urls import patterns, include, url
from django.contrib import admin
address = 'benz'
urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
	url(r'^'+address+'/backend/login/', 'backend.views.login'),
	url(r'^'+address+'/backend/problem/', 'backend.views.problem'),
	url(r'^'+address+'/backend/userList/', 'backend.views.userList'),
	url(r'^'+address+'/backend/getProblemId/', 'backend.views.getProblemId'),
	url(r'^'+address+'/backend/setProblemId/', 'backend.views.setProblemId'),
	url(r'^'+address+'/backend/sign/', 'backend.views.sign'),
    url(r'^'+address+'/backend/sign_rank/', 'backend.views.sign_rank'),
	url(r'^'+address+'/backend/taskList/', 'backend.views.taskList'),
	url(r'^'+address+'/backend/addUser/', 'backend.views.addUser'),
	url(r'^'+address+'/backend/loginAction/', 'backend.views.loginAction'),
	url(r'^'+address+'/backend/userList/', 'backend.views.userSource'),
	url(r'^'+address+'/backend/saveUser/', 'backend.views.saveUser'),
	url(r'^'+address+'/backend/getUserMessage/', 'backend.views.getUserMessage'),
	url(r'^'+address+'/backend/getTaskMessage/', 'backend.views.getTaskMessage'),
	url(r'^'+address+'/backend/deleteTask/', 'backend.views.deleteTask'),
	url(r'^'+address+'/backend/deleteUser/', 'backend.views.deleteUser'),
	url(r'^'+address+'/backend/saveTask/', 'backend.views.saveTask'),
	url(r'^'+address+'/backend/taskList/', 'backend.views.taskList'),
	url(r'^'+address+'/backend/quitAction/', 'backend.views.quitAction'),
	url(r'^'+address+'/portal/login/', 'portal.views.login'),
	url(r'^'+address+'/portal/loginAction/', 'portal.views.loginAction'),
    url(r'^'+address+'/portal/mapMode/', 'portal.views.mapMode'),
	url(r'^'+address+'/portal/portal/', 'portal.views.portal'),
	url(r'^'+address+'/portal/problem/', 'portal.views.problem'),
	url(r'^'+address+'/portal/result/', 'portal.views.result'),
	url(r'^'+address+'/backend/signMessage/', 'backend.views.signMessage'),
	url(r'^'+address+'/portal/littleCource/', 'portal.views.littleCource'),
	url(r'^'+address+'/portal/bigBuy/', 'portal.views.bigBuy'),
	url(r'^'+address+'/portal/option/', 'portal.views.option'),
	url(r'^'+address+'/portal/hotPerson/', 'portal.views.hotPerson'),
	url(r'^'+address+'/portal/spaceRebuild/', 'portal.views.spaceRebuild'),
	url(r'^'+address+'/portal/throwMoney/', 'portal.views.throwMoney'),
	url(r'^'+address+'/portal/getFirst/', 'portal.views.getFirst'),
	url(r'^'+address+'/portal/fiveCan/', 'portal.views.fiveCan'),
	url(r'^'+address+'/portal/perfectIn/', 'portal.views.perfectIn'),
	url(r'^'+address+'/portal/driveSuccess/', 'portal.views.driveSuccess'),
	url(r'^'+address+'/portal/upload_location/', 'portal.views.upload_position'),
	url(r'^'+address+'/portal/wx_login_portal/', 'portal.views.wx_login_portal'),
	url(r'^'+address+'/portal/taskList/', 'portal.views.taskList'),
    url(r'^'+address+'/portal/update_access_token/','portal.views.update_access_token'),
    url(r'^'+address+'/portal/wxconfig/','portal.views.wxconfig'),
	url(r'^'+address+'/spot/quitAction/', 'spot.views.quitAction'),
	url(r'^'+address+'/spot/loginAction/', 'spot.views.loginAction'),
	url(r'^'+address+'/spot/login/', 'spot.views.login'),
	url(r'^'+address+'/spot/index/', 'spot.views.index'),
	url(r'^'+address+'/spot/chooseList/', 'spot.views.chooseList'),
	url(r'^'+address+'/spot/chooseTask/', 'spot.views.chooseTask'),
    url(r'^'+address+'/spot/taskTerm', 'spot.views.taskTerm'),
    url(r'^'+address+'/spot/addUser', 'spot.views.addUser'),
    url(r'^'+address+'/spot/addScore', 'spot.views.addScore'),
	url(r'^'+address+'/spot/register/', 'spot.views.register'),
	url(r'^'+address+'/spot/editScore/', 'spot.views.editScore'),
	url(r'^'+address+'/spot/superUserAdd/', 'spot.views.superUserAdd'),
	url(r'^'+address+'/spot/superUserAdd/', 'spot.views.testArea'),

)
